CREATE TABLE IF NOT EXISTS `analyses` (
	`id` text PRIMARY KEY NOT NULL,
	`vinted_id` text NOT NULL,
	`url` text NOT NULL,
	`title` text NOT NULL,
	`description` text,
	`price` real NOT NULL,
	`brand` text,
	`size` text,
	`condition` text,
	`seller_username` text NOT NULL,
	`seller_rating` real,
	`seller_sales_count` integer,
	`photos` text NOT NULL,
	`photo_quality_score` integer NOT NULL,
	`photo_analysis` text NOT NULL,
	`authenticity_score` integer NOT NULL,
	`authenticity_flags` text NOT NULL,
	`authenticity_confidence` text NOT NULL,
	`market_price_low` real,
	`market_price_high` real,
	`market_price_avg` real,
	`market_price_sources` text,
	`market_price_confidence` text,
	`opportunity_score` integer NOT NULL,
	`margin` real,
	`margin_percent` real,
	`signals` text NOT NULL,
	`suggested_offer` real,
	`negotiation_script` text,
	`negotiation_arguments` text,
	`negotiation_tone` text,
	`resale_price` real,
	`resale_estimated_days` integer,
	`resale_tips` text,
	`resale_platforms` text,
	`status` text DEFAULT 'ANALYZED' NOT NULL,
	`analyzed_at` integer DEFAULT (unixepoch()) NOT NULL,
	`updated_at` integer DEFAULT (unixepoch()) NOT NULL
);
--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS `analyses_vinted_id_unique` ON `analyses` (`vinted_id`);