export type {
	SellerReliability,
	SellerBadge,
	VintedSeller,
	VintedArticleData,
	PhotoQuality,
	AuthenticityCheck,
	SourceListing,
	MarketPriceSource,
	RetailPrice,
	MarketPrice,
	SignalType,
	OpportunitySignal,
	Opportunity,
	NegotiationTone,
	Negotiation,
	PlatformRelevance,
	ResalePlatform,
	Resale,
	AnalysisStatus,
	ConfidenceLevel,
	AIDetection,
	AnalysisResult,
} from './types/index.js'
