#!/bin/bash

# Vinted AI Assistant - Installation Script for Unix systems (macOS/Linux)
# This script handles both fresh installation and server restart

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

# Get the root directory (parent of installer/)
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/../.." && pwd)"

print_header() {
    echo ""
    echo -e "${CYAN}╔════════════════════════════════════════════════════════╗${NC}"
    echo -e "${CYAN}║${NC}        ${BLUE}Vinted AI Assistant - Installer${NC}                ${CYAN}║${NC}"
    echo -e "${CYAN}╚════════════════════════════════════════════════════════╝${NC}"
    echo ""
}

print_step() {
    echo -e "${BLUE}▶${NC} $1"
}

print_success() {
    echo -e "${GREEN}✓${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}⚠${NC} $1"
}

print_error() {
    echo -e "${RED}✗${NC} $1"
}

# Check if already installed
check_installation() {
    local node_modules_exists=false
    local env_exists=false
    local db_exists=false

    if [ -d "$ROOT_DIR/node_modules" ]; then
        node_modules_exists=true
    fi

    if [ -f "$ROOT_DIR/apps/backend/.env" ]; then
        # Check if .env contains an API key
        if grep -qE "(GOOGLE_GENERATIVE_AI_API_KEY|OPENAI_API_KEY)=.+" "$ROOT_DIR/apps/backend/.env" 2>/dev/null; then
            env_exists=true
        fi
    fi

    if [ -f "$ROOT_DIR/apps/backend/data/vinted-ai.db" ]; then
        db_exists=true
    fi

    if $node_modules_exists && $env_exists && $db_exists; then
        return 0 # Installed
    else
        return 1 # Not installed
    fi
}

# Install nvm and Node.js LTS
install_nvm_node() {
    if command -v node &> /dev/null; then
        print_success "Node.js already installed ($(node --version))"
        return 0
    fi

    print_step "Installing nvm..."
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.3/install.sh | bash

    # Source nvm immediately (CRITICAL - otherwise nvm is not available)
    export NVM_DIR="$HOME/.nvm"
    [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
    [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"

    print_step "Installing Node.js LTS..."
    nvm install --lts
    nvm use --lts
    nvm alias default 'lts/*'

    print_success "Node.js $(node --version) installed"
}

# Install pnpm
install_pnpm() {
    print_step "Installing/updating pnpm..."

    # Enable corepack (included with Node.js >= 16.9)
    corepack enable 2>/dev/null || true

    # Install pnpm via npm if corepack didn't work
    if ! command -v pnpm &> /dev/null; then
        npm install -g pnpm
    fi

    # Update to latest version
    pnpm self-update 2>/dev/null || true

    # Export PATH for pnpm
    export PNPM_HOME="${HOME}/.local/share/pnpm"
    export PATH="$PNPM_HOME:$PATH"

    print_success "pnpm $(pnpm --version) installed"
}

# Install Bun if not present
install_bun() {
    if command -v bun &> /dev/null; then
        print_success "Bun already installed ($(bun --version))"
        return 0
    fi

    print_step "Installing Bun..."

    if command -v curl &> /dev/null; then
        curl -fsSL https://bun.sh/install | bash
        # Source the updated PATH
        export BUN_INSTALL="${HOME}/.bun"
        export PATH="$BUN_INSTALL/bin:$PATH"
    else
        print_error "Cannot install Bun. Please install curl first."
        exit 1
    fi

    print_success "Bun installed"
}

# Ask for API key
configure_api_key() {
    echo ""
    echo -e "${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo -e "${BLUE}Configuration de l'API Google Gemini${NC}"
    echo -e "${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo ""
    echo -e "1. Ouvre ${CYAN}https://aistudio.google.com/apikey${NC}"
    echo "2. Connecte-toi avec ton compte Google"
    echo "3. Clique sur \"Create API Key\""
    echo "4. Copie la clé générée"
    echo ""

    read -p "Colle ta clé API Gemini ici: " api_key

    if [ -z "$api_key" ]; then
        print_error "La clé API ne peut pas être vide"
        exit 1
    fi

    # Create .env file
    mkdir -p "$ROOT_DIR/apps/backend/data"
    cat > "$ROOT_DIR/apps/backend/.env" << EOF
# Vinted AI Assistant - Configuration
# Generated by installer on $(date)

GOOGLE_GENERATIVE_AI_API_KEY=$api_key
PORT=3000
EOF

    print_success "Configuration enregistrée dans apps/backend/.env"
}

# Install npm dependencies
install_dependencies() {
    print_step "Installation des dépendances npm..."
    cd "$ROOT_DIR"
    # Auto-approve builds for native dependencies (e.g., sharp)
    export PNPM_APPROVE_BUILDS=true
    pnpm install
    print_success "Dépendances installées"
}

# Setup database
setup_database() {
    print_step "Création de la base de données..."
    cd "$ROOT_DIR"
    pnpm --filter backend db:migrate
    print_success "Base de données créée"
}

# Build extension
build_extension() {
    print_step "Compilation de l'extension Chrome..."
    cd "$ROOT_DIR"
    pnpm --filter extension build
    print_success "Extension compilée dans apps/extension/dist/"
}

# Open install guide
open_guide() {
    local guide_path="$ROOT_DIR/installer/INSTALL_GUIDE.html"

    if [ -f "$guide_path" ]; then
        print_step "Ouverture du guide d'installation de l'extension..."

        if [[ "$OSTYPE" == "darwin"* ]]; then
            open "$guide_path"
        elif [[ "$OSTYPE" == "linux-gnu"* ]]; then
            if command -v xdg-open &> /dev/null; then
                xdg-open "$guide_path" &
            elif command -v gnome-open &> /dev/null; then
                gnome-open "$guide_path" &
            else
                print_warning "Ouvre manuellement: $guide_path"
            fi
        fi
    fi
}

# Start server
start_server() {
    echo ""
    echo -e "${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo -e "${GREEN}  Démarrage du serveur...${NC}"
    echo -e "${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo ""
    echo -e "Le serveur va démarrer sur ${CYAN}http://localhost:3000${NC}"
    echo ""
    echo -e "${YELLOW}Pour arrêter le serveur : Ctrl+C${NC}"
    echo ""

    cd "$ROOT_DIR"
    pnpm --filter backend dev
}

# Main installation flow
main() {
    print_header

    cd "$ROOT_DIR"

    if check_installation; then
        echo -e "${GREEN}Installation existante détectée !${NC}"
        echo ""
        print_step "Démarrage du serveur..."
        start_server
    else
        echo -e "${YELLOW}Première installation détectée${NC}"
        echo ""

        # Step 1: Install system dependencies
        print_step "Vérification des dépendances système..."
        install_nvm_node
        install_pnpm
        install_bun

        # Step 2: Configure API key
        configure_api_key

        # Step 3: Install npm dependencies
        install_dependencies

        # Step 4: Setup database
        setup_database

        # Step 5: Build extension
        build_extension

        # Step 6: Open guide
        open_guide

        echo ""
        echo -e "${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
        echo -e "${GREEN}  Installation terminée avec succès !${NC}"
        echo -e "${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
        echo ""
        echo -e "📁 Extension Chrome: ${CYAN}$ROOT_DIR/apps/extension/dist/${NC}"
        echo ""
        echo -e "${YELLOW}Prochaine étape:${NC} Suis le guide pour installer l'extension Chrome"
        echo ""

        # Step 7: Start server
        start_server
    fi
}

# Run main
main
